Repository honeycombio/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#86 [refinery] Update docs on pod recycling for config changes
  charts/refinery/README.md
Labels: type: documentation, version: no bump

#84 Update README in gh-pages branch
  README.md
Labels: type: maintenance, version: no bump

#87 [refinery] Upgrade Refinery to v1.8.0, for configurable MaxBatchSize
  charts/refinery/Chart.yaml
  charts/refinery/README.md
  charts/refinery/sample-configs/config_complete.yaml
  charts/refinery/values.yaml
Labels: type: enhancement, version: bump minor
