Repository honeycombio/helm-charts, pull requests merged in 2022-07, with the labels that each got.

#147 [Refinery] Enable extra volume configurations in deployment config
  charts/refinery/templates/deployment.yaml
  charts/refinery/values.yaml
Labels: type: enhancement, version: bump minor, status: revision needed, status: oncall

#155 Add helm namespace to templates
  charts/opentelemetry-collector/templates/configmap.yaml
  charts/opentelemetry-collector/templates/deployment.yaml
  charts/opentelemetry-collector/templates/hpa.yaml
  charts/opentelemetry-collector/templates/secret.yaml
  charts/opentelemetry-collector/templates/service.yaml
  charts/opentelemetry-collector/templates/serviceaccount.yaml
Labels: type: enhancement, version: bump minor

#159 update honeycomb k8s agent to 2.5.3
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: bump patch

#160 Prepare Honeycomb v1.5.2
  charts/honeycomb/CHANGELOG.md
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: no bump
