Repository honeycombio/helm-charts, pull requests merged in 2022-11, with the labels that each got.

#200 [agent] update agent version to 2.5.5
  charts/honeycomb/Chart.yaml
Labels: version: bump patch

#203 [refinery] bump app version to 1.19.0
  charts/refinery/Chart.yaml
  charts/refinery/ci/cache-overrun-strat-resize-values.yaml
  charts/refinery/values.yaml
Labels: version: bump minor

#205 [agent] update agent version to 2.5.6
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: bump patch

#206 [agent] Prepare v1.5.5 release
  charts/honeycomb/CHANGELOG.md
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: bump patch

#210 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#211 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
