Repository honeycombio/helm-charts, pull requests merged in 2022-10, with the labels that each got.

#192 maint: add release file
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#194 [refinery] Update to set redis host based on release name
  charts/refinery/templates/configmap-config.yaml
  charts/refinery/values.yaml
Labels: version: bump patch

#195 [refinery] Add more refinery scenarios
  charts/refinery/ci/ingress-values.yaml
Labels: version: no bump

#198 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
Labels: type: maintenance, version: no bump, merge at will
