Repository honeycombio/helm-charts, pull requests merged in 2022-02, with the labels that each got.

#103 Update ST chart to support 1.12.1
  charts/secure-tenancy/Chart.yaml
  charts/secure-tenancy/README.md
  charts/secure-tenancy/templates/configmap.yaml
  charts/secure-tenancy/values.yaml
Labels: version: bump minor, status: review needed

#109 Remove secure-tenancy chart owner override
  .github/CODEOWNERS
Labels: type: maintenance, version: no bump

#107 Prepare otel collector chart v1.1.0 release
  charts/opentelemetry-collector/CHANGELOG.md
  charts/opentelemetry-collector/Chart.yaml
Labels: type: maintenance, version: bump minor

#110 Prepare refinery v1.5.0 release
  charts/refinery/CHANGELOG.md
  charts/refinery/Chart.yaml
Labels: type: maintenance, version: bump minor

#113 [honeycomb] Bump honeycomb agent from 2.3.1 to 2.3.2
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: bump patch

#117 [refinery] bump app version to 1.10.0
  charts/refinery/Chart.yaml
  charts/refinery/sample-configs/config_complete.yaml
  charts/refinery/values.yaml
Labels: version: bump minor

#119 [refinery] docs: fix typo in changelog
  charts/refinery/CHANGELOG.md
Labels: type: documentation, version: no bump

#123 maint: use supported ubuntu image for circle
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#125 [refinery] Bump image to v1.11.0
  charts/refinery/Chart.yaml
  charts/refinery/values.yaml
Labels: type: maintenance, version: bump minor
