Repository honeycombio/helm-charts, pull requests merged in 2022-08, with the labels that each got.

#162 Custom rules configmap
  charts/refinery/templates/configmap-rules.yaml
  charts/refinery/templates/deployment.yaml
  charts/refinery/values.yaml
Labels: type: enhancement, status: revision needed, status: oncall

#163 Fix a TOML->YAML conversion whoopsie
  charts/refinery/sample-configs/rules_complete.yaml
Labels: type: maintenance, version: no bump, merge at will

#166 [refinery] Prepare v1.12.0 release
  charts/refinery/CHANGELOG.md
  charts/refinery/Chart.yaml
Labels: type: maintenance, version: bump minor

#164 [opentelemetry-collector] Swap order of hpa spec.metrics
  charts/opentelemetry-collector/templates/hpa.yaml
Labels: version: bump patch, status: oncall

#169 separate yaml layers to help parsing
  charts/refinery/sample-configs/rules_complete.yaml
Labels: type: documentation, type: maintenance

#167 docs: document metrics.interval configuration option
  charts/honeycomb/README.md
  charts/honeycomb/values.yaml
Labels: type: documentation, status: oncall

#172 [refinery] prep release 1.12.1
  charts/refinery/CHANGELOG.md
  charts/refinery/Chart.yaml
Labels: type: maintenance, version: no bump
