Repository honeycombio/helm-charts, pull requests merged in 2022-01, with the labels that each got.

#91 [honeycomb] add pod labels
  charts/honeycomb/README.md
  charts/honeycomb/templates/daemonset.yaml
  charts/honeycomb/values.yaml
Labels: type: enhancement, version: bump minor

#98 [honeycomb] bump agent version to 2.3.1
  charts/honeycomb/Chart.yaml
Labels: version: bump patch

#99 Prepare v1.3.0
  RELEASING.md
  charts/honeycomb/CHANGELOG.md
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: no bump
