Repository honeycombio/helm-charts, pull requests merged in 2022-09, with the labels that each got.

#175 Add Helm namespace metadata
  charts/refinery/templates/configmap-config.yaml
  charts/refinery/templates/configmap-rules.yaml
  charts/refinery/templates/deployment-redis.yaml
  charts/refinery/templates/deployment.yaml
  charts/refinery/templates/hpa.yaml
  charts/refinery/templates/ingress-beta.yaml
  charts/refinery/templates/ingress-grpc.yaml
  charts/refinery/templates/ingress.yaml
  charts/refinery/templates/service-redis.yaml
  charts/refinery/templates/service.yaml
  charts/refinery/templates/serviceaccount.yaml
Labels: type: enhancement, version: bump minor, status: revision needed, status: oncall

#178 Update sample config with new fields
  charts/refinery/sample-configs/config_complete.yaml
Labels: type: documentation, version: no bump

#182 [refinery] bump app version to 1.17.0
  charts/refinery/Chart.yaml
  charts/refinery/values.yaml
Labels: version: bump minor

#184 [honeycomb] update k8s agent version to v2.5.4
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: bump patch

#185 [honeycomb] Prepare v1.5.3 release
  charts/honeycomb/CHANGELOG.md
  charts/honeycomb/Chart.yaml
Labels: type: maintenance, version: bump patch
