Repository honeycombio/helm-charts, pull requests merged in 2023-11, with the labels that each got.

#307 maint: [network-agent] reduce apiGroups in rbac
  charts/network-agent/README.md
  charts/network-agent/templates/cluster_role.yaml
Labels: chart: network agent

#311 maint: Bump hny network agent image to v0.0.25-alpha
  charts/network-agent/Chart.yaml
Labels: type: maintenance

#312 rel: Prepare v0.0.5 release of network agent
  charts/network-agent/CHANGELOG.md
  charts/network-agent/Chart.yaml
Labels: type: maintenance

#313 feat: Add support for custom pod annotations to network agent
  charts/network-agent/templates/daemonset.yaml
  charts/network-agent/values.yaml
Labels: type: enhancement

#314 rel: Prepare v0.0.6 release of network agent
  charts/network-agent/CHANGELOG.md
  charts/network-agent/Chart.yaml
Labels: type: maintenance, no-changelog
