Repository honeycombio/helm-charts, pull requests merged in 2024-12, with the labels that each got.

#399 maint(refinery): update appVersion to 2.9
  charts/refinery/Chart.yaml
Labels: chart: refinery

#400 feat(refinery): add deployment-marker support
  charts/refinery/Chart.yaml
  charts/refinery/README.md
  charts/refinery/templates/NOTES.txt
  charts/refinery/templates/deployment-marker-job.yaml
  charts/refinery/values.yaml
Labels: type: enhancement

#402 docs(refinery): note experimental nature of deploy marker
  charts/refinery/Chart.yaml
  charts/refinery/README.md
Labels: type: documentation, version: bump patch

#408 fix(refinery): deployment marker image pull secrets and job name uniqueness
  charts/refinery/Chart.yaml
  charts/refinery/templates/deployment-marker-job.yaml
Labels: type: enhancement
